# .goreleaser.yml
# https://carlosbecker.com/posts/multi-platform-docker-images-goreleaser-gh-actions/
builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - linux
    goarch:
    - amd64
    - arm64
dockers:
  - skip_push: false
  - image_templates: ["ghcr.io/wwami-pipeline/nwhcp-server:{{ .Version }}-amd64"]
    use: docker
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates: ["ghcr.io/wwami-pipeline/nwhcp-server:{{ .Version }}-arm64"]
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
docker_manifests:
  - name_template: ghcr.io/wwami-pipeline/nwhcp-server:{{ .Version }}
    image_templates:
      - ghcr.io/wwami-pipeline/nwhcp-server:{{ .Version }}-amd64
      - ghcr.io/wwami-pipeline/nwhcp-server:{{ .Version }}-arm64
  - name_template: ghcr.io/wwami-pipeline/nwhcp-server:latest
    image_templates:
      - ghcr.io/wwami-pipeline/nwhcp-server:{{ .Version }}-amd64
      - ghcr.io/wwami-pipeline/nwhcp-server:{{ .Version }}-arm64